### ISSUE TITLE
[mboxparsing] Index error if artifact names contain '\n'

### ISSUE THREAD

**Issue by bockthom** [se-passau/codeface-extraction#10]
### Description:

When artifact names contain the '\n' character, the mbox parsing fails.

### Example:

In the `gcc_feature` analysis, there is the following FeatureExpression, which occurs in "libiberty/safe-ctype.c":

```C
!('\n' == 0x0A && ' ' == 0x20 && '0' == 0x30 && 'A' == 0x41 && 'a' == 0x61 && '!' == 0x21 && EOF == -1)
```
As python interprets the \n within the feature-expression name as a line break, the line is split into two lines there and then the second line part does not have 13 resp. 14 elements any more, which leads to the following error message:
```python
File "/mnt/codeface-extraction/mbox_parsing/mbox_parsing.py", line 70, in __get_artifacts
    commit_set.add((commit_seperated[12], commit_seperated[13]))
IndexError: list index out of range
```
### Suggested solution:

Before accessing `commit_seperated[12]`, check whether the currently processed "line" has exactly 16 elements. If the currently processed "line" does not have 16 elements, just ignore the current line (and, hence, do not search for the problematic artifact then).

**Comment by clhunsen** [comment]
Okay, I cannot reproduce the problem in my Codeface VM, but I narrowed down the problem: We use line-by-line reading of the commits file, which does not work in this case. When switching to the CSV functionality of Python, it will probably work as it works with proper escaping.

I have commit in the pipeline, will push it tomorrow.
