### ISSUE TITLE
Output files of the JIRA issue processing

### ISSUE THREAD

**Issue by bockthom** [se-passau/codeface-extraction#33]
While working on #32, I just recognized the following:

The JIRA issue processing creates several `.list` output files. I am not sure what the difference is and whether it is worth to create all of them:

https://github.com/se-passau/codeface-extraction/blob/c8d948151ca2a03c7daf3811d1d0a902550c0013/issue_processing/jira_issue_processing.py#L127-L128

https://github.com/se-passau/codeface-extraction/blob/c8d948151ca2a03c7daf3811d1d0a902550c0013/issue_processing/jira_issue_processing.py#L754

What I understand is:
- `issues-jira.list` contains the output we finally use in coronet, its format is consistent with `issues-github.list`
- `bugs-jira.list` is similar to `issues-jira.list` but just contains bugs

However, I don't understand the following:
- `issues.list` What is this file for? It has a completely different format than the remaining files.
- `issue-jira.list` This file is created always, but stays empty all the time. Why is it created? Can we just remove it and stop creating it?

I would be very glad if you could help me to understand what's going on here. I hope you still remember what was going on in #17 as you have reviewed it @clhunsen @ecklbarb.

**Comment by bockthom** [comment]
After discussing this with @ecklbarb, we came to the following conclusion:
- Don't create the empty file `issue-jira.list` anymore, as it is never used.
- Don't run the archaic issues export (resulting in `issues.list`) any more (just comment it out).
- Don't run the gephi export any more as we don't have such an export for other parts of the extraction (just comment it out).

**Comment by clhunsen** [comment]
Thanks for taking care of this issue. Can you please reference this issue in your latest commit message (https://github.com/bockthom/codeface-extraction/commit/0ea4e75bdd56344b475b1fdb5160dc13049bdf21) for the sake of completeness? 

Afterwards, this issue can be closed, I guess.

**Comment by bockthom** [comment]
> Thanks for taking care of this issue. Can you please reference this issue in your latest commit message ([bockthom@0ea4e75](https://github.com/bockthom/codeface-extraction/commit/0ea4e75bdd56344b475b1fdb5160dc13049bdf21)) for the sake of completeness?

Sure, I will do that. Thanks for pointing that out, this is a good idea!
