### ISSUE TITLE
[mboxparsing] Search for 'files' mentioned in e-mails

### ISSUE THREAD

**Issue by bockthom** [se-passau/codeface-extraction#9]
Currently, it is not possible to search for file names occurring in e-mails -- we can only search for artifacts (which are `functions` in the `proximity` analysis and `features` in the `feature` analysis, already configured by the Codeface configuration), and we can also search for those artifacts together with their file path.

As we can search for features and functions, but not for files, we need to introduce an additional option to search for file names in e-mails (e.g., ``--file``). I would suggest two different analyses:
(1) search for plain file names (i.e., only the file name, not the complete path)
(2) search for file names incl. path (as we usually use the complete file path as artifact name when analyzing files)

The reason for (1) is that possibly not the full paths are used in e-mails, as they would be too long, but just the name of the file if it is known which file is talked about.
(2) is easy to achieve, as we can combine the new option for files ``--file`` with the already existing ``--filepath``option here.

Example output:
```
file,                  artifcat,  messageId
--------------------------------------------------------
"path/to/file/file.c", "file.c", "<message-id-1>"
```
(1) When using ``--file``, the example output means:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;``"file.c"`` occurs in ``"<message-id-1>".``
(2) When using ``--file --filepath``, the output means:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;``"path/to/file/file.c"`` occurs in ``"<message-id-1>".``

---
The above described behaviour is easy to implement: 
- Add an additional configuration option ``--file``
- Adjust the `__get_artifacts` function: 
  - Pass an additional parameter specifying whether ``--file`` is configured or not.
  - If ``--file`` is configured, choose the `file` column of the commit data as artifact, otherwise chose the `artifact` column of the commit data as artifact (as hitherto).
- Adjust the `parse` function:
  - Pass an additional parameter specifying whether ``--file`` is configured or not.
  - If ``--file`` is configured, choose `mboxparsing_file.list` resp. `mboxparsing_file_filepath.list` as output file.

As the described functionality is very helpful and easy to implement, I will implement this soon and open a pull request then. Stay tuned!

**Comment by clhunsen** [comment]
Why adding the additional CLI flag and not running the mbox parsing for the artifact `file` additionally when the tagging is set to `proximity` in the given configuration file – analogously to the artifact mapping in the network library?

**Comment by bockthom** [comment]
> Why adding the additional CLI flag and not running the mbox parsing for the artifact `file` additionally when the tagging is set to `proximity` in the given configuration file – analogously to the artifact mapping in the network library?

This would also be a possible solution, but I still would prefer the CLI flag for the following reasons:
- When running the mbox parsing for `file` additionally, we have to rewrite the `parse` function (or the `run` function) to be able to perform `function` and `file` analyses consecutively and produce separate output files. Then, possibly, those functions are not that easy to read and understand any more.
- When adding an CLI flag, we can run all the mbox parsing analyses separately. So, just in the case that some problems occur in one of the two analyses or the analysis takes way too much time and we do not need the analysis, we don't have to run it.

I am waiting for your comments on that. As I will need this functionality very soon, we should also come to a decision soon, so that I can start implementing that...
